# Generated by Django 5.2.3 on 2025-07-11 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_name_profile_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='discord_tag',
            field=models.CharField(blank=True, help_text='e.g. User#1234', max_length=32),
        ),
        migrations.AddField(
            model_name='profile',
            name='steam_id',
            field=models.CharField(blank=True, help_text='Your 64-bit SteamID', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='steam_profile',
            field=models.URLField(blank=True, help_text='Full Steam Community URL'),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitch_channel',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='ExternalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('STEAM', 'Steam'), ('DISCORD', 'Discord'), ('TWITCH', 'Twitch'), ('OTHER', 'Other')], max_length=10)),
                ('identifier', models.CharField(help_text='Could be a username, ID, or full URL', max_length=100)),
                ('url', models.URLField(blank=True, help_text='Full profile link (if applicable)')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_accounts', to='main_app.profile')),
            ],
            options={
                'unique_together': {('profile', 'service', 'identifier')},
            },
        ),
    ]
