# Generated by Django 5.2.3 on 2025-07-12 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_profile_discord_tag_profile_steam_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='guild',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='guild',
            index=models.Index(fields=['name'], name='main_app_gu_name_e75e07_idx'),
        ),
        migrations.AddField(
            model_name='profilerole',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.profile'),
        ),
        migrations.AddField(
            model_name='profilerole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.role'),
        ),
        migrations.AlterUniqueTogether(
            name='profilerole',
            unique_together={('profile', 'role')},
        ),
    ]
