# Generated by Django 5.2.3 on 2025-07-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_profilerole_role_alter_guild_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_recurring',
        ),
        migrations.RemoveField(
            model_name='event',
            name='recurrence_rule',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='discord_tag',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='steam_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='steam_profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='twitch_channel',
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='required_roles',
            field=models.CharField(blank=True, help_text='Comma-separated list of roles needed', max_length=200),
        ),
        migrations.AlterField(
            model_name='eventtemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='eventtemplate',
            name='default_roles',
            field=models.CharField(blank=True, help_text='Comma-separated roles: DPS,Healer,Tank', max_length=200),
        ),
        migrations.AlterField(
            model_name='eventtemplate',
            name='default_time',
            field=models.DurationField(help_text='Default duration, e.g. 2 hours'),
        ),
        migrations.AlterField(
            model_name='externalaccount',
            name='identifier',
            field=models.CharField(help_text='Username, ID, or full URL', max_length=100),
        ),
        migrations.AlterField(
            model_name='externalaccount',
            name='url',
            field=models.URLField(blank=True, help_text='Full profile link if applicable'),
        ),
        migrations.AlterField(
            model_name='guild',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='guild',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('LEADER', 'Guild Leader'), ('OFFICER', 'Officer'), ('MEMBER', 'Member'), ('RECRUIT', 'Recruit'), ('TRIAL', 'Trial')], default='MEMBER', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='role_signed_up',
            field=models.CharField(blank=True, help_text='Role this member plans to fill, e.g. DPS', max_length=50),
        ),
    ]
