# Generated by Django 5.2.3 on 2025-07-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_event_is_recurring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='membership',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('LEADER', 'Guild Leader'), ('OFFICER', 'Officer'), ('MEMBER', 'Member'), ('RECRUIT', 'Recruit'), ('TRIAL', 'Trial')], default='RECRUIT', max_length=10),
        ),
    ]
